version: "3.9"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD:
      DB_NAME: banhang
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: banhang
    ports:
      - "3306:3306"
